# Define the default target
all: install

# Install target
install:
	@echo "Running install.sh script..."
	./setup.sh

# Clean target (optional)
clean:
	@echo "Cleaning up..."
	rm -rf some_directory_or_files
